### ISSUE TITLE
Hangs up on Git Bash (Windows)

### ISSUE THREAD

**Issue by gsscoder** [jakubroztocil/httpie#828] opened 2020-01-03 14:06 UTC
First of all let me thankyou for wonderful project! It works perfectly on any platform I use.

Anyway on **Windows** (installed via `pip`), when it runs on **Git Bash** doesn't produce any output and blocks the shell. On **PowerShell** works perfectly.

System is **Windows 10**, **GitBash** is the latest at the moment of writing.

Have a nice day

**Comment by Zygimantass** [comment] 2020-04-20 13:08
I can confirm this is true, it does indeed not work on Git Bash, going to triage it now.

**Comment by jakubroztocil** [comment] 2020-04-20 14:14
What do you get when you run this?
```bash
$ python3 -c 'import sys; print(sys.stdin.isatty())'
```

**Comment by Zygimantass** [comment] 2020-04-20 14:21
Yep, it returns False

**Comment by Zygimantass** [comment] 2020-04-20 14:22
Maybe we should consider throwing a warning or something if the terminal is not TTY?

**Comment by jakubroztocil** [comment] 2020-04-20 14:30
HTTPie uses `stdin` as a way to pass in data (e.g. `echo hello | http httpbin.org/post`) and the `isatty()` check also returns `False` for redirected `stdin`.

So the problem is not non-TTY invocations in general, but in the fact that Python running inside Git Bash incorrectly reports `False` even though `stdin` is connected to the terminal.


https://httpie.org/docs#redirected-input
https://httpie.org/docs#best-practices
https://docs.python.org/3/library/os.html?highlight=isatty#os.isatty

**Comment by Zygimantass** [comment] 2020-04-20 14:38
So this should probably be closed as it's not HTTPie's bug, right?

**Comment by jakubroztocil** [comment] 2020-04-20 14:45
Yes — reported here:  https://github.com/git-for-windows/git/issues/2594

**Closed by jakubroztocil** 2020-04-20 14:45 UTC

**Comment by jakubroztocil** [comment] 2020-04-22 08:40
It turns out it’s a known issue in Git for Windows v2.26.2:

> This issue is listed specifically in the [Known Issues in our Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):
> 
> > * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).
> 
> The installer even suggests (on the page titled "Configuring the terminal emulator to use with Git Bash") to
> 
> > Use Windows' default console window
> > [...] which works well with Win32 console programs such as interactive Python or node.js [...]

- https://github.com/git-for-windows/git/issues/2594#issuecomment-616677790
- https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues

**Comment by gsscoder** [comment] 2020-04-30 13:54
OK, thank you @jakubroztocil!

**Comment by yanakey** [comment] 2022-02-20 01:34
Upgraded python and httpie to the latest versions today and got this issue.
I've just added `alias http='winpty http'` to my `~/.bashrc` and it works again.
Thanks!
