### ISSUE TITLE
Feature request: Quick way to set nested JSON values

### ISSUE THREAD

**Issue by BrandonY** [jakubroztocil/httpie#346] opened 2015-04-29 00:19 UTC
Let's say an API takes several values, like in this example call:

    {
       "name": "Fred",
       "age", 27,
       "pets" : {
          "penguins": 2,
          "dogs":1
       }
    }

I can reference name and age easily:

    $> http PUT https://www.example.com/users/1  name=Phil age=25

But editing pets is uglier:

    $>   http PUT https://www.example.com/users/1 pets:='{"penguins":2, "dogs":1}'

I'd like to do something like one of these:

    $> http PUT https://www.example.com/users/1 pets.penguins=2  pets.dogs=1
    $> http PUT https://www.example.com/users/1 pets="penguins=2 dogs=1"
    $> http PUT https://www.example.com/users/1 pets\penguins=2 pets\dogs=1

That said, "." and "\" could conceivably be part of a JSON key, so maybe that's not actually a good idea?

**Comment by matleh** [comment] 2015-06-01 13:27
Maybe have a look at JSONPath (http://goessner.net/articles/JsonPath/) for syntax inspiration.

**Comment by sigmavirus24** [comment] 2015-06-01 15:02
Duplicate of #78

**Comment by jakubroztocil** [comment] 2015-06-26 15:47
Closing this in favor of #78

**Closed by jakubroztocil** 2015-06-26 15:47 UTC
Labels: duplicate, feature

**Comment by isidentical** [comment] 2022-01-24 12:10
🎉 This feature is now publicly available in [HTTPie for Terminal 3.0](https://httpie.io/blog/httpie-3.0.0):

👉🏻  https://httpie.io/docs/cli/nested-json
