### ISSUE TITLE
Fails to print request or response when server returns

### ISSUE THREAD

**Issue by tlbdk** [jakubroztocil/httpie#601] opened 2017-08-09 12:24 UTC
We have a graphgl API where we are doing a multipart upload and get "413 Request Entity Too Large" when the file is file is too large, this works with curl, but not with httpie. The request headers and body is not even shown.

It should be noted that we are going via Google Cloud http load balancer before hitting Nginx that blocks the request. Also I redacted server names from the debug output.

```
http -v -f POST https://hostname/api/graphql query='mutation RootMutationType($carId: Int!, $token: String!) { carUploadImage(carId: $carId, token: $token) { id,imageFilename}}' variables='{"carId": 1, "token": "..."}' file@./testfile.dat

http: error: ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')) while doing POST request to URL: https://hostname/api/graphql
```

```
curl -v https://hostname/api/graphql \
-H "Content-Type:multipart/form-data" \
-F 'query=mutation RootMutationType($carId: Int!, $token: String!) { carUploadImage(carId: $carId, token: $token) { id,imageFilename}}' \
-F 'variables={\"carId\":1,\"token\":\"...\"};type=application/json' \
-F 'file=@./testfile.dat'
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to hostname (1.2.3.4) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: hostname
* Server certificate: RapidSSL SHA256 CA
* Server certificate: GeoTrust Global CA
> POST /api/graphql HTTP/1.1
> Host: hostname
> User-Agent: curl/7.51.0
> Accept: */*
> Content-Length: 104858299
> Expect: 100-continue
> Content-Type:multipart/form-data; boundary=------------------------200e4faa1c52a317
>
< HTTP/1.1 413 Request Entity Too Large
< Server: nginx/1.13.3
< Date: Wed, 09 Aug 2017 12:12:02 GMT
< Content-Type: text/html
< Content-Length: 199
< Strict-Transport-Security: max-age=15724800; includeSubDomains;
< Via: 1.1 google
< Alt-Svc: clear
< Connection: close
<
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.13.3</center>
</body>
</html>
* Curl_http_done: called premature == 0
* Closing connection 0
```

**Comment by ikalnytskyi** [comment] 2017-10-11 14:57
Is it a duplicate of https://github.com/jakubroztocil/httpie/issues/600 ?

**Comment by jakubroztocil** [comment] 2019-08-31 10:35
Closing in favour of #600

**Closed by jakubroztocil** 2019-08-31 10:35 UTC
