### ISSUE TITLE
config.json cannot be load occassionally in multiprocess usecase

### ISSUE THREAD

**Issue by onriv** [jakubroztocil/httpie#812] opened 2019-10-31 14:09 UTC
It seems that during http request, the file config.json will be cleaned and update. In multiprocess usecase, sometimes httpie would read an empty config file and occurs an error.
The thrown exception are:

```python
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\httpie\config.py", line 47, in load
    data = json.load(f)
  File "c:\python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\http.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\httpie\__main__.py", line 11, in main
    sys.exit(main())
  File "c:\python36\lib\site-packages\httpie\core.py", line 193, in main
    if env.config.default_options:
  File "c:\python36\lib\site-packages\httpie\context.py", line 84, in config
    self._config.load()
  File "c:\python36\lib\site-packages\httpie\config.py", line 96, in load
    super(Config, self).load()
  File "c:\python36\lib\site-packages\httpie\config.py", line 51, in load
    (type(self).__name__, str(e), self.path)
ValueError: Invalid Config JSON: Expecting value: line 1 column 1 (char 0) [D:\Users\xxxx\AppData\Roaming\\httpie\config.json]
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\httpie\config.py", line 47, in load
    data = json.load(f)
  File "c:\python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\http.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\httpie\__main__.py", line 11, in main
    sys.exit(main())
  File "c:\python36\lib\site-packages\httpie\core.py", line 193, in main
    if env.config.default_options:
  File "c:\python36\lib\site-packages\httpie\context.py", line 84, in config
    self._config.load()
  File "c:\python36\lib\site-packages\httpie\config.py", line 96, in load
    super(Config, self).load()
  File "c:\python36\lib\site-packages\httpie\config.py", line 51, in load
    (type(self).__name__, str(e), self.path)
ValueError: Invalid Config JSON: Expecting value: line 1 column 1 (char 0) [D:\Users\xxxx\AppData\Roaming\\httpie\config.json]
```

**Comment by jwgcooke** [comment] 2019-11-25 16:58
This is a duplicate of #788

**Closed** 2019-12-02 16:43 UTC

**Comment by jakubroztocil** [comment] 2019-12-02 16:45
Fixed in `master`, thanks!
